# -*- coding: utf-8 -*-
"""Text Similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBG9DLISOssWFReuJ9odb_kk6JhLO0ht
"""

import pandas as pd
from sentence_transformers import SentenceTransformer, util


df = pd.read_csv('DataNeuron_Text_Similarity.csv')


print(df.columns)


df.columns = ['para1', 'para2']


model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')


embeddings1 = model.encode(df['para1'].tolist(), convert_to_tensor=True)
embeddings2 = model.encode(df['para2'].tolist(), convert_to_tensor=True)


cosine_scores = util.cos_sim(embeddings1, embeddings2)


similarity_raw = cosine_scores.diag().cpu().numpy()


similarity_normalized = (similarity_raw + 1) / 2


df['similarity'] = similarity_normalized


df.to_csv('TextSimilarity_with_Scores.csv', index=False)

import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

